# BigTable configuration
bigtable.thread-count=16
#number of rows to process in each batch within a thread range
bigtable.subrange-size=10000
#max number of chained batches
bigtable.batch-limit=5

# bigtable.blocks-last-key=ffffffffffffffff
bigtable.blocks-last-key=00000000000186A0
bigtable.entries-last-key=ffffffffffffffff
#87 chars
bigtable.tx-last-key=zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
#40/16 chars
bigtable.tx-by-addr-last-key=zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz/zzzzzzzzzzzzzzzz

bigtable.project-id=mainnet-beta
bigtable.instance-id=solana-ledger
bigtable.credentials=/app/solana-tencent-e042e478aa66.json


# Tencent Cloud Object Storage configuration
cos-utils.tencent.id-key=test
cos-utils.tencent.secret-key=test
cos-utils.tencent.bucket-name=test
cos-utils.tencent.endpoint=http://cos.ap-chengdu.myqcloud.com
cos-utils.tencent.region=ap-chengdu
cos-utils.http-client.max-concurrency=200
# seconds
cos-utils.http-client.connection-acquisition-timeout=60
# seconds
cos-utils.http-client.write-timeout=60
# seconds
cos-utils.http-client.connection-timeout=240

# Directory to read files from
geyser-plugin.input-directory=/input/storage
