services:
  syncer-local-files:
    build:
      context: ./syncer
      dockerfile: Dockerfile
    volumes:
      - /data:/data
      - ./syncer/config.properties:/app/config.properties
    command: geyser-to-cos
    depends_on:
      - validator-with-geyser-plugin

  validator-with-geyser-plugin:
    build:
      context: ./validator
      dockerfile: GeyserPlugin.Dockerfile
    volumes:
      - /data:/data
