services:
  bigtable-emulator:
    build:
      context: ./bigtable-emulator
    ports:
      - "8086:8086"
    environment:
      BIGTABLE_EMULATOR_HOST: bigtable-emulator:8086
      GOOGLE_APPLICATION_CREDENTIALS: "/usr/local/bin/solana-data-migration-1b9caa70b7cc.json"

  validator:
    build:
      context: ./validator
      dockerfile: Dockerfile
    environment:
      #  IMPORTANT: Choose between bigtable-emulator or solana-bigtable-hbase-adapter, depending on your setup
      BIGTABLE_EMULATOR_HOST: bigtable-emulator:8086
      # BIGTABLE_EMULATOR_HOST: solana-bigtable-hbase-adapter:50051
      GOOGLE_APPLICATION_CREDENTIALS: "/usr/local/bin/solana-data-migration-1b9caa70b7cc.json"
    depends_on:
      #  IMPORTANT: Add / remove the following dependencies depending on your setup
      - bigtable-emulator
      # - hbase
      # - solana-bigtable-hbase-adapter

  hbase:
    build:
      context: ./hbase
      dockerfile: Dockerfile
    ports:
      - "16010:16010"
      - "16020:16020"
      - "16030:16030"
      - "2181:2181"
      - "9090:9090"
    stdin_open: true
    tty: true
    volumes:
      - ./input:/input

  syncer-bigtable:
    image: solana-syncer
    build:
      context: ./syncer
      dockerfile: Dockerfile
    volumes:
      - ./syncer/config.properties:/app/config.properties
      - ./syncer/solana-tencent-e042e478aa66.json:/app/solana-tencent-e042e478aa66.json
    environment:
      JVM_ARGS: "-Xmx26g"
    command: read-source=bigtable
    # environment:
      # BIGTABLE_EMULATOR_HOST: bigtable-emulator:8086
    # depends_on:
      #- bigtable-emulator

  syncer-local-files:
    image: solana-syncer
    build:
      context: ./syncer
      dockerfile: Dockerfile
    volumes:
      - /data:/data
      - ./syncer/config.properties:/app/config.properties
    command: read-source=local-files
    # environment:
     # BIGTABLE_EMULATOR_HOST: bigtable-emulator:8086
    # depends_on:
     # - bigtable-emulator

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  minio-bucket-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin123) do sleep 5; done;
      /usr/bin/mc mb myminio/mybucket;
      /usr/bin/mc policy set public myminio/mybucket;
      exit 0;
      "

  solana-lite-rpc:
    build:
      context: ./solana-lite-rpc
      dockerfile: Dockerfile
    ports:
      - "8899:8899"
      - "8900:8900"
    depends_on:
      - hbase

  solana-bigtable-hbase-adapter:
    build:
      context: ./solana-bigtable-hbase-adapter
      dockerfile: Dockerfile
    environment:
      HBASE_HOST: hbase:9090
    ports:
      - "50051:50051"
    depends_on:
      - hbase
