services:
  bigtable-emulator:
    build:
      context: ./bigtable-emulator
    ports:
      - "8086:8086"
    environment:
      BIGTABLE_EMULATOR_HOST: bigtable-emulator:8086
      GOOGLE_APPLICATION_CREDENTIALS: "/usr/local/bin/bigtable-service-account-key.json"

  validator:
    build:
      context: ./validator
      dockerfile: Dockerfile
    environment:
      #  IMPORTANT: Choose between bigtable-emulator or solana-bigtable-hbase-adapter, depending on your setup
      BIGTABLE_EMULATOR_HOST: bigtable-emulator:8086
#      BIGTABLE_EMULATOR_HOST: solana-bigtable-hbase-adapter:50051
      GOOGLE_APPLICATION_CREDENTIALS: "/usr/local/bin/bigtable-service-account-key.json"
    depends_on:
      #  IMPORTANT: Add / remove the following dependencies depending on your setup
      - bigtable-emulator
      - hbase
      - solana-bigtable-hbase-adapter

  hbase:
    build:
      context: ./hbase
      dockerfile: Dockerfile
    ports:
      - "16010:16010"
      - "16020:16020"
      - "16030:16030"
      - "2181:2181"
      - "9090:9090"
    stdin_open: true
    tty: true
    volumes:
      - ./input:/input

  syncer-bigtable:
    image: solana-syncer
    build:
      context: ./syncer
      dockerfile: Dockerfile
    volumes:
      - ./syncer/config.properties:/app/config.properties
      - ./syncer/bigtable-service-account-key.json:/app/bigtable-service-account-key.json
    command: read-source=bigtable # use-emulator=true
    environment:
      JVM_ARGS: "-Xmx26g"
      # BIGTABLE_EMULATOR_HOST: bigtable-emulator:8086
    # depends_on:
      #- bigtable-emulator

  syncer-local-files:
    image: solana-syncer
    build:
      context: ./syncer
      dockerfile: Dockerfile
    volumes:
      - /data:/data
      - ./syncer/config.properties:/app/config.properties
    command: read-source=local-files
    # environment:
     # BIGTABLE_EMULATOR_HOST: bigtable-emulator:8086
    # depends_on:
     # - bigtable-emulator

  solana-lite-rpc:
    build:
      context: ./solana-lite-rpc
      dockerfile: Dockerfile
    ports:
      - "8899:8899"
      - "8900:8900"
    depends_on:
      - hbase

  solana-bigtable-hbase-adapter:
    build:
      context: ./solana-bigtable-hbase-adapter
      dockerfile: Dockerfile
    environment:
      HBASE_HOST: hbase:9090
    ports:
      - "50051:50051"
    depends_on:
      - hbase
