services:
  bigtable-emulator:
    build:
      context: ./bigtable-emulator
    ports:
      - "8086:8086"
    environment:
      BIGTABLE_EMULATOR_HOST: bigtable-emulator:8086
      GOOGLE_APPLICATION_CREDENTIALS: "/usr/local/bin/solana-data-migration-1b9caa70b7cc.json"

  validator:
    build:
      dockerfile: validator/Dockerfile
    environment:
      # BIGTABLE_EMULATOR_HOST: bigtable-emulator:8086
      BIGTABLE_EMULATOR_HOST: solana-bigtable-hbase-adapter:50051
      GOOGLE_APPLICATION_CREDENTIALS: "/usr/local/bin/solana-data-migration-1b9caa70b7cc.json"
    depends_on:
      # - bigtable-emulator
      - hbase
      - solana-bigtable-hbase-adapter

  hbase:
    build:
      context: ./hbase
      dockerfile: Dockerfile
    ports:
      - "16010:16010"
      - "16020:16020"
      - "16030:16030"
      - "2181:2181"
      - "9090:9090"
    stdin_open: true
    tty: true
    volumes:
      - ./output:/output

  syncer:
    build:
      dockerfile: Dockerfile
      context: ./syncer
    environment:
      BIGTABLE_EMULATOR_HOST: bigtable-emulator:8086
    command: sleep 3600
    ports:
      - "9090:9090"
    volumes:
      - ./output/sequencefile:/output/sequencefile
    depends_on:
      - bigtable-emulator

  solana-lite-rpc:
    build:
      context: ./solana-lite-rpc
      dockerfile: Dockerfile
    ports:
      - "8899:8899"
      - "8900:8900"
    depends_on:
      - hbase

  solana-bigtable-hbase-adapter:
    build:
      context: ./solana-bigtable-hbase-adapter
      dockerfile: Dockerfile
    environment:
      HBASE_HOST: hbase:9090
    ports:
      - "50051:50051"
    depends_on:
      - hbase
