services:
  bigtable-emulator:
    build:
      context: ./bigtable-emulator
    ports:
      - "8086:8086"
    environment:
      BIGTABLE_EMULATOR_HOST: bigtable-emulator:8086
      GOOGLE_APPLICATION_CREDENTIALS: "/usr/local/bin/solana-data-migration-1b9caa70b7cc.json"

  validator:
    build:
      dockerfile: validator/Dockerfile
    environment:
      BIGTABLE_EMULATOR_HOST: bigtable-emulator:8086
      GOOGLE_APPLICATION_CREDENTIALS: "/usr/local/bin/solana-data-migration-1b9caa70b7cc.json"
    depends_on:
      - bigtable-emulator

  # hbase:
  #   build:
  #     dockerfile: hbase/Dockerfile
  #   ports:
  #     - "16010:16010"
  #     - "16020:16020"
  #     - "16030:16030"
  #     - "2181:2181"
  #   volumes:
  #     - ./data:/data
  #   command: ["/bin/bash", "-c", "start-hbase.sh; hbase shell", wait]
  #   networks:
  #     - app-network

  pipeline:
    build:
      dockerfile: Dockerfile
      context: ./pipeline
    environment:
      BIGTABLE_EMULATOR_HOST: bigtable-emulator:8086
      # GOOGLE_APPLICATION_CREDENTIALS: "/usr/local/bin/solana-data-migration-1b9caa70b7cc.json"
    ports:
      - "9090:9090"
    volumes:
      - ./output:/output
    depends_on:
      - bigtable-emulator
